/****************************************************************************
 **
 ** This file is part of yFiles for HTML 1.1.0.1.
 ** 
 ** yWorks proprietary/confidential. Use is subject to license terms.
 **
 ** Copyright (c) 2013 by yWorks GmbH, Vor dem Kreuzberg 28, 
 ** 72070 Tuebingen, Germany. All rights reserved.
 **
 ***************************************************************************/
(typeof define=='function'?define:(function(dependencies, fn){fn();}))(['yfiles/lang'],function(){
  {
    if(!yfiles.mappings)yfiles.mappings={};
    yfiles.lang.copyOwnTo({
      '_$_sj':["parseTemplateBindings","$a"],
      '_$_tj':["WithKey","$a"],
      '_$_uqc':["style","$Hg"],
      '_$_arc':["width","$Kg"],
      '_$_qrc':["height","$Og"],
      '_$_qvc':["preferredSize","$Mi"],
      '_$_sid':["getMinimumSize","$oo"],
      '_$_rtd':["setSize","$at"],
      '_$_dxd':["createTemplateContext","$lu"],
      '_$_zxd':["getPreferredSize","$Du"],
      '_$_bse':["center","$uD"],
      '_$_ote':["content","$eE"],
      '_$_kxe':["controlStyleRenderer","$YF"],
      '_$_jwf':["mapperRegistryTag","$fT"],
      '_$_jgi':["getTag","$hxb"],
      '_$_sxi':["getRenderSize","$VFb"],
      '_$_xxi':["createRenderer","$bGb"],
      '_$_kgj':["arrange","$kKb"],
      '_$_dnj':["setArrangeRect","$cNb"],
      '_$_lnj':["getOutlineShape","$kNb"],
      '_$_woj':["getPreferredSizeWithContext","$RNb"],
      '_$_uqj':["onPropertyChanged","$MOb"],
      '_$_jyj':["getRenderTemplate","$pSb"],
      '_$_xzj':["updateContent","$cTb"],
      '_$_xdk':["onItemFocusedChanged","$aVb"],
      '_$_fek':["onItemSelectedChanged","$iVb"],
      '_$_sfk':["onItemHighlightedChanged","$TVb"],
      '_$_hjk':["updateFor","$EXb"],
      '_$_wjk':["lookupContext","$TXb"],
      '_$_akk':["initializeFrom","$XXb"],
      '_$_ocl':["TemplateStyleBase","ZUB"],
      '_$_pcl':["GraphItemTemplateContextBase","AVB"],
      '_$_qcl':["GraphItemControlExtensions","BVB"],
      '_$_rcl':["MapperBasedUserTagProvider","DVB"],
      '_$_scl':["ITemplateLabelStyle","EVB"],
      '_$_tcl':["TemplateLabelStyleRenderer","GVB"],
      '_$_ucl':["ITemplateNodeStyle","IVB"],
      '_$_vcl':["TemplateNodeStyleRenderer","KVB"],
      '_$_wcl':["ITemplatePortStyle","MVB"],
      '_$_xcl':["TemplatePortStyleRenderer","OVB"],
      '_$$_fdb':["item","$dg"],
      '_$$_reb':["canvas","$Mg"],
      '_$$_web':["insets","$Pg"],
      '_$$_qfb':["autoFlip","$lh"],
      '_$$_xfb':["styleTag","$wh"],
      '_$$_yfb':["template","$xh"],
      '_$$_igb':["renderSize","$Wh"],
      '_$$_qgb':["minimumSize","$ki"],
      '_$$_xgb':["outlineShape","$Di"],
      '_$$_fib':["setTag","$cm"],
      '_$$_glb':["content","$eE"],
      '_$$_mmb':["isFlipped","$VG"],
      '_$$_nmb':["labelText","$XG"],
      '_$$_snb':["itemFocused","$NJ"],
      '_$$_cob':["isUpsideDown","$fL"],
      '_$$_dob':["itemSelected","$gL"],
      '_$$_xpb':["itemHighlighted","$eQ"],
      '_$$_sqb':["renderTemplateId","$hS"],
      '_$$_hyb':["setArrangeRect","$cNb"],
      '_$$_myb':["onPropertyChanged","$MOb"],
      '_$$_oyb':["onLabelTextChanged","$nPb"],
      '_$$_qyb':["updateContent","$cTb"],
      '_$$_syb':["writeBackLabelText","$HUb"],
      '_$$_tyb':["updateFor","$EXb"],
      '_$$_vyb':["initializeFrom","$XXb"],
      '_$$_fdc':["yfiles.drawing","Root"],
      '_$$_gdc':["IUIElementStyle","CVB"],
      '_$$_hdc':["TemplateLabelStyle","FVB"],
      '_$$_idc':["LabelTemplateContext","HVB"],
      '_$$_jdc':["TemplateNodeStyle","JVB"],
      '_$$_kdc':["NodeTemplateContext","LVB"],
      '_$$_ldc':["TemplatePortStyle","NVB"],
      '_$$_mdc':["PortTemplateContext","PVB"]
    },yfiles.mappings);
  }
  return undefined;
});
