/****************************************************************************
 **
 ** This file is part of yFiles for HTML 1.1.0.1.
 ** 
 ** yWorks proprietary/confidential. Use is subject to license terms.
 **
 ** Copyright (c) 2013 by yWorks GmbH, Vor dem Kreuzberg 28, 
 ** 72070 Tuebingen, Germany. All rights reserved.
 **
 ***************************************************************************/
(typeof define=='function'?define:(function(dependencies, fn){fn();}))(['yfiles/lang'],function(){
  {
    if(!yfiles.mappings)yfiles.mappings={};
    yfiles.lang.copyOwnTo({
      '_$_mnc':["pen","$Tf"],
      '_$_cpc':["brush","$og"],
      '_$_dpc':["color","$pg"],
      '_$_dqc':["inset","$yg"],
      '_$_yrc':["radius","$Vg"],
      '_$_stc':["drawShadow","$Oh"],
      '_$_scg':["provideRadiusHandle","$lW"],
      '_$_wsg':["isRatio","$Ueb"],
      '_$_ltg':["getHeight","$ifb"],
      '_$_ewi':["getImage","$eFb"],
      '_$_ccj':["getPreserveAspectRatio","$fIb"],
      '_$_mdl':["ArcEdgeStyleRenderer","XWB"],
      '_$_ndl':["IArcEdgeStyle","ZWB"],
      '_$_odl':["IBevelNodeStyle","AXB"],
      '_$_pdl':["BevelNodeStyleRenderer","BXB"],
      '_$_qdl':["IImageNodeStyle","DXB"],
      '_$_rdl':["ImageNodeStyleRenderer","EXB"],
      '_$_sdl':["IPanelNodeStyle","GXB"],
      '_$_tdl':["PanelNodeStyleRenderer","IXB"],
      '_$_udl':["IShinyPlateNodeStyle","JXB"],
      '_$_vdl':["ShinyPlateNodeStyleRenderer","LXB"],
      '_$$_qd':["WithRenderer","$a"],
      '_$$_rd':["WithPenAndHeight","$b"],
      '_$$_sd':["WithRendererPenAndHeight","$c"],
      '_$$_td':["WithColor","$b"],
      '_$$_ud':["WithRendererAndColor","$c"],
      '_$$_vd':["WithPath","$a"],
      '_$$_wd':["WithRenderer","$b"],
      '_$$_xd':["WithImage","$c"],
      '_$$_yd':["WithImageAndRenderer","$d"],
      '_$$_zd':["WithColorAndInsetsColor","$c"],
      '_$$_ae':["WithRendererAndColor","$d"],
      '_$$_be':["WithBrush","$b"],
      '_$$_ce':["WithColor","$c"],
      '_$$_de':["WithBrushAndPen","$d"],
      '_$$_ee':["WithRendererBrushRadiusAndInsets","$e"],
      '_$$_fe':["WithRendererColorRadiusAndInsets","$f"],
      '_$$_ucb':["pen","$Tf"],
      '_$$_sdb':["brush","$og"],
      '_$$_vdb':["color","$pg"],
      '_$$_zdb':["image","$wg"],
      '_$$_beb':["inset","$yg"],
      '_$$_heb':["ratio","$Fg"],
      '_$$_seb':["height","$Og"],
      '_$$_veb':["insets","$Pg"],
      '_$$_hfb':["radius","$Vg"],
      '_$$_ggb':["drawShadow","$Oh"],
      '_$$_ygb':["outlineShape","$Di"],
      '_$$_jhb':["labelInsetsColor","$xj"],
      '_$$_hsb':["provideHeightHandle","$kW"],
      '_$$_iec':["yfiles.drawing","Root"],
      '_$$_jec':["ArcEdgeStyle","YWB"],
      '_$$_kec':["BevelNodeStyle","CXB"],
      '_$$_lec':["ImageNodeStyle","FXB"],
      '_$$_mec':["PanelNodeStyle","HXB"],
      '_$$_nec':["ShinyPlateNodeStyle","KXB"]
    },yfiles.mappings);
  }
  return undefined;
});
