/****************************************************************************
 **
 ** This file is part of yFiles for HTML 1.1.0.1.
 ** 
 ** yWorks proprietary/confidential. Use is subject to license terms.
 **
 ** Copyright (c) 2013 by yWorks GmbH, Vor dem Kreuzberg 28, 
 ** 72070 Tuebingen, Germany. All rights reserved.
 **
 ***************************************************************************/
'use strict';("undefined"!=typeof define?define:function(w,D){D()})([],function(){window.yfiles=window.yfiles||{};window.yfiles.util=yfiles.util||{};yfiles.productname="yFiles for HTML";yfiles.version="1.1.0.1";window.yfiles.util.getObjectNS=function(b,a){for(var i=b.split("."),e=window,g=0,m=i.length;g<m;g++)e="undefined"===typeof e[i[g]]?a&&g===m-1?e[i[g]]=a:e[i[g]]={}:e[i[g]];return e};var w="";window.yfiles.TypeDefinition=function(b,a){this.callback=b;this.creator=a;this.namespaceStack=w};window.yfiles.ClassDefinition=
function(b){window.yfiles.TypeDefinition.call(this,b,yfiles.lang.Class)};window.yfiles.ClassDefinition.prototype=new window.yfiles.TypeDefinition;window.yfiles.InterfaceDefinition=function(b){this.creator=yfiles.lang.Trait;window.yfiles.TypeDefinition.call(this,b,yfiles.lang.Trait)};window.yfiles.InterfaceDefinition.prototype=new window.yfiles.TypeDefinition;window.yfiles.StructDefinition=function(b){this.creator=yfiles.lang.Struct;window.yfiles.TypeDefinition.call(this,b,yfiles.lang.Struct)};window.yfiles.StructDefinition.prototype=
new window.yfiles.TypeDefinition;window.yfiles.EnumDefinition=function(b){this.creator=yfiles.lang.Enum;window.yfiles.TypeDefinition.call(this,b,yfiles.lang.Enum)};window.yfiles.EnumDefinition.prototype=new window.yfiles.TypeDefinition;window.yfiles.AttributeDefinition=function(b){window.yfiles.TypeDefinition.call(this,b,yfiles.lang.Attribute)};window.yfiles.AttributeDefinition.prototype=new window.yfiles.TypeDefinition;var D=[];window.yfiles.getLoadedClasses=function(){return D};window.yfiles.replaceTypeDefinition=
function(b,a,i,e){var g=b.value;if(g instanceof yfiles.TypeDefinition){var m=g.callback,t=g.creator,o=yfiles.util.browser.featuresupport.canReplacePropertyDescriptorOnTheFly,p=e||i,l=b.$$indexName$||b.value&&b.value.$$indexName$;Object.defineProperty(a,i,{get:function(){var b=w;w=a.$class&&a.$class.fullName||g.namespaceStack;D.push(w+"."+p);Object.defineProperty(a,i,{get:function(){throw Error("Cyclic declaration!");},configurable:!0});var e=m();l&&(e.$$indexName$=l);var v=t(p,e);o?Object.defineProperty(a,
i,{value:v,configurable:!1}):(setTimeout(function(){Object.defineProperty(a,i,{value:v,configurable:!1})},0),Object.defineProperty(a,i,{get:function(){return v},configurable:!0}));if(v.$clinit)try{v.$clinit(),delete v.$clinit}catch(z){throw console.log(z),Error("Could not initialize "+v);}w=b;return v},configurable:!0})}else Object.defineProperty(a,i,b)};var J={};window.yfiles.module=function(b,a){var i=yfiles.mappings&&yfiles.mappings[b],e=i&&Array.isArray(i),g=b;i&&(e?(b=i[1],g=i[0]):b=g=i);w=g;
var m=yfiles.util.getObjectNS(b),t;e&&(t=yfiles.util.getObjectNS(i[0]));var o={};a(o);if(o.$meta)i=o.$meta,delete o.$meta,J[b]?J[b].push(i):J[b]=[i];Object.getOwnPropertyNames(o).forEach(function(a){var b=Object.getOwnPropertyDescriptor(o,a),e=b.value,i;g=a;if(e instanceof yfiles.TypeDefinition&&(i=yfiles.mappings&&yfiles.mappings[a]))yfiles.typeinfo&&-1!=yfiles.debuglevel&&(b.$$indexName$=a),Array.isArray(i)?(a=i[1],g=i[0]):(g=a=i,i=void 0);window.yfiles.replaceTypeDefinition(b,m,a,g);t&&Object.defineProperty(t,
i&&i[0]||a,{get:function(){return m[a]}})});w=""};yfiles.module("yfiles",function(){yfiles.register=function(b,a){yfiles.util.getObjectNS(b,a)}});yfiles.module("yfiles.lang.fn",function(b){b.id=function(a){return a};b.join=function(a,b,e){return function(){return b(a.apply(e,arguments))}};b.combine=function(){var a=arguments;return function(){for(var b=0;b<a.length;b++)a[b].apply(this,arguments)}}});yfiles.module("yfiles.lang",function(b){function a(g){for(var b=[],i=1<g.length?g.splice(1):!1,e=0,
g=g[0];e<g;e++)b.push(!1===i?[]:a(i));return b}b.defineInvisibleProperty=function(a,b,i){Object.defineProperty(a,b,{value:i,enumerable:!1,writable:!0,configurable:!0})};b.isFunction=function(a){return"function"===typeof a};b.isArray=function(a){return a&&(Array.isArray(a)||a instanceof Array||"[object Array]"===Object.prototype.toString.call(a))};b.isNumber=function(a){return a instanceof Number};b.isObject=function(a){return a instanceof Object&&"object"===typeof a};b.isPrimitive=function(a){a=typeof a;
return"number"===a||"boolean"===a||"string"===a||"undefined"===a};b.copyOwnTo=function(a,b,i){i=i||yfiles.lang.fn.id;Object.getOwnPropertyNames(a).forEach(function(e){var p=Object.getOwnPropertyDescriptor(a,e),p=i(p,e)||p;window.yfiles.replaceTypeDefinition(p,b,e)});return b};b.newMultiArray=function(){return a(Array.prototype.slice.call(arguments))};var i=b.requestAnimationFrameCore=function(){return window.requestAnimationFrame||window.mozRequestAnimationFrame||window.msRequestAnimationFrame||window.oRequestAnimationFrame||
window.webkitRequestAnimationFrame||function(a){return setTimeout(a,16)}}();b.requestAnimationFrame=function(a){return i.call(window,a)};var e=b.cancelRequestAnimationFrameCore=function(){return window.cancelAnimationFrame||window.cancelRequestAnimationFrame||window.mozCancelAnimationFrame||window.mozCancelRequestAnimationFrame||window.msCancelAnimationFrame||window.msCancelRequestAnimationFrame||window.oCancelAnimationFrame||window.oCancelRequestAnimationFrame||window.webkitCancelAnimationFrame||
window.webkitCancelRequestAnimationFrame||function(a){clearTimeout(a)}}();b.cancelRequestAnimationFrame=function(a){e.call(window,a)};b.getType=function(a){if(a.getClass)return a.getClass();var b=typeof a;return"number"===b||"boolean"===b||"string"===b?yfiles.lang.Class.forName("yfiles.lang."+b.charAt(0).toUpperCase()+b.substr(1)):a instanceof Array?yfiles.lang.Object.$class.makeArrayType(1):yfiles.lang.Object.$class}});yfiles.module("yfiles.util.browser.featuresupport",function(b){b.canDecompileFunction=
function(){return/abc(.|\n)*xyz/.test(function(){})}();b.canReplacePropertyDescriptorOnTheFly=function(){var a=Object.create({},{test:{get:function(){Object.defineProperty(a,"test",{value:"hello"});return 42},configurable:!0}});try{return 42===a.test&&"hello"===a.test}catch(b){return!1}}()});yfiles.module("yfiles.lang.HashCode",function(b){var a=0;b.newHashCode=function(){return a++};b.of=function(a){if("string"===typeof a){for(var b=0,g=0,m=a.length;g<m;g++)b=(31*b|0)+a.charCodeAt(g)|0;return b}if(a.hashCode)return a.hashCode()}});
(function(){var b=Object.prototype.toString;Object.defineProperty(Object.prototype,"equals",{value:function(a){return b.call(this)===b.call(a)&&this==a},enumerable:!1,writable:!0,configurable:!0});Object.defineProperty(Object.prototype,"hashCode",{value:function(){if(void 0!==this.$yfiles___hashcode)return this.$yfiles___hashcode;var a=yfiles.lang.HashCode.newHashCode();Object.defineProperty(this,"$yfiles___hashcode",{value:a,enumerable:!1,writable:!0,configurable:!0});return a},enumerable:!1,writable:!0,
configurable:!0});Object.defineProperties(String.prototype,{hashCode:{value:function(){for(var a=0,b=0,e=this.length;b<e;b++)a=(31*a|0)+this.charCodeAt(b)|0;return a},enumerable:!1,writable:!0,configurable:!0},equals:{value:function(a){return"[object String]"===b.call(a)&&a==this},writable:!0,configurable:!0},compareTo:{value:function(a){if("[object String]"!==b.call(a))return 1;if(a==this)return 0;a=this.localeCompare(a);return 0!==a?a:1}},compareToObject:{value:function(a){return this.compareTo(a)}}});
Object.defineProperties(Number.prototype,{hashCode:{value:function(){return Math.round(this)}},equals:{value:function(a){return"[object Number]"===b.call(a)&&a==this}},compareTo:{value:function(a){return"[object Number]"!==b.call(a)?1:a==this?0:this<a?-1:1}},compareToObject:{value:function(a){return this.compareTo(a)}}});Object.defineProperties(Boolean.prototype,{hashCode:{value:function(){return this?1:0}},equals:{value:function(a){return"[object Boolean]"===b.call(a)&&this==a}},compareTo:{value:function(a){return"[object Boolean]"!==
b.call(a)?1:a==this?0:this?1:-1}},compareToObject:{value:function(a){return this.compareTo(a)}}})})();yfiles.module("yfiles.lang",function(b){function a(c,d,f){function a(){if(this instanceof d.constructor){if("yfiles.lang.Object"!==$super.$class.name){if(yfiles.typeinfo&&-1!=yfiles.debuglevel&&0<arguments.length)throw Error("Argument error: too many arguments in constructor. Expected 0 got "+arguments.length);$super.apply(this,arguments)}}else throw Error('Missing "new" operator at object instantiation.');
}f||(f={isAnonymous:!1});if("string"!==typeof c&&!d)d=c,c="AnonymousClass$"+U++,f.isAnonymous=!0;f.isFlagsEnum||(f.isFlagsEnum=!1);var n=0<w.length?w+"."+c:c,$super=yfiles.lang.Object||Object;if(d.$extends)$super=d.$extends,delete d.$extends;c=d.hasOwnProperty("$static")?d.$static:{};delete d.$static;var b=d.hasOwnProperty("$abstract")?d.$abstract:!1;delete d.$abstract;f.$meta||(f.$meta={});if(d.$meta)f.$meta[n]=d.$meta,delete d.$meta;var h=null;if(d.hasOwnProperty("$with"))h=d.$with,delete d.$with,
O.isTrait(h)||(h=O({$with:h}));yfiles.typeinfo&&-1!=yfiles.debuglevel&&yfiles.lang.Object&&(K(d,!1,d.$$indexName$,n,!1,$super,h),K(c,!1,d.$$indexName$,n,!0),delete d.$$indexName$);yfiles.mappings&&(c=L(c),d=L(d,$super,h));null!==h&&p(n,d,h,b,$super.prototype,f);var e=null;if(d.constructor&&!y(d.constructor))if(d.constructor.$meta)f.$meta["ctor.constructor"]=d.constructor.$meta,d.constructor=d.constructor.value;else{if(e=d.constructor,d.constructor=e["default"]||a,d.constructor.$meta)delete e["default"],
f.$meta["ctor.constructor"]=d.constructor.$meta,d.constructor=d.constructor.value}else if(!d.hasOwnProperty("constructor"))d.constructor=a;var u=d.constructor,g=function(){var c=arguments;return function(d,f){for(var a=0,x=c.length;a<x;a++){var n=c[a](d,f);n&&(d=n)}return d}};u.prototype="yfiles.lang.Class"==n&&!yfiles.lang.Class?G(d,$super,g(C(f),z,E(n))):G(d,Object.create($super.prototype),g(C(f),z,V($super.prototype),E(n)));$super&&$super.$class&&"Object"!=$super.$class.name&&$super.$class.isAbstract&&
!b&&i($super.prototype,d,n);G(c,u,g(C(f),z,E(n)));e&&Object.getOwnPropertyNames(e).forEach(function(c){var d=e[c];if(!y(d))f.$meta["ctor."+c]=d.$meta,d=d.value;d.displayName=c;d.prototype=u.prototype;Object.defineProperty(u,c,{value:d,writable:!1});yfiles.mappings&&(c=yfiles.mappings[c],"undefined"!==typeof c&&Object.defineProperty(u,c,{value:d}))});u.displayName=n;u.toString=function(){return n};v(n,u,$super,h,f);R=null;return u}function i($super,d,f,a){var n=Object.getPrototypeOf($super),b,j;j=
null!==n&&n.getClass&&(b=n.getClass())&&b.isAbstract&&b!==yfiles.lang.Object.$class?i(n,$super,f,!0):[];Object.getOwnPropertyNames($super).forEach(function(d){var f=Object.getOwnPropertyDescriptor($super,d)||yfiles.lang.Object.getPropertyDescriptor($super,d);r.isAbstract(f)&&j.push(d)});n=j.length;for(b=0;b<n;b++){var h=j[b];if(null!=h){var e=a?Object.getOwnPropertyDescriptor(d,h)||yfiles.lang.Object.getPropertyDescriptor(d,h):d[h];if(!e||r.isAbstract(e)){if(!a)throw Error("Class "+f+" does not implement abstract property/method "+
h);}else j[b]=null}}return j}function e(){k||(k="yfiles"in window&&yfiles.system);return k}function g(c,d,f,a,n,b){var j=n.getAttributesFor((f===k.MemberTypes.CONSTRUCTOR?"ctor.":"")+d);if(f===k.MemberTypes.FIELD)return new k.FieldInfo(d,a,n,j,b);if(f===k.MemberTypes.METHOD)return new k.MethodInfo(d,a,n,j,c[d],b,!1);if(f===k.MemberTypes.CONSTRUCTOR)return new k.ConstructorInfo(d,a,n,j,c[d],b);if(f===k.MemberTypes.PROPERTY){var h=Object.getOwnPropertyDescriptor(c,d),f=h.get?new k.MethodInfo(d,a,n,
j,b?function(){return c[d]}:function(){return this[d]},b,!0):null,b=h.set?new k.MethodInfo(d,a,n,j,b?function(f){return c[d]=f}:function(c){return this[d]=c},b,!0):null;return new k.PropertyInfo(d,a,n,j,f,b)}return f===k.MemberTypes.TYPE_INFO?c[d].$class:null}function m(c,d,f){c=Object.getOwnPropertyDescriptor(d,c);if(c.get||c.set)return k.MemberTypes.PROPERTY;c=c.value;return y(c)?c.prototype&&c.prototype===f.Object.prototype?k.MemberTypes.CONSTRUCTOR:c.$class?k.MemberTypes.NESTED_TYPE:k.MemberTypes.METHOD:
k.MemberTypes.FIELD}function t(c,d){return function(){var f=arguments,a=function(){var a=d();if(!y(c))if(c.value)c=c.value;else throw Error("Cannot call attribute constructor "+c);c.apply(a,f);return a};if(this instanceof P)return a();a.init=function(c){return function(){for(var d=a(),f=Object.getOwnPropertyNames(c),b=0,e=f.length;b<e;b++){var u=f[b];d[u]=c[u]}return d}};return a}}function o(c,d){var f,a,b;for(f=2,a=arguments.length;f<a;f++){b=arguments[f];for(var H=2;H<a;H++)if(f!=H){var j=arguments[H];
j&&j.$class.types[b.$class.name]&&(arguments[f]=null)}}var h={};for(f=2,a=arguments.length;f<a;f++)(b=arguments[f])&&b.$members&&Object.getOwnPropertyNames(b.$members).forEach(function(c){var f=C(d)(Object.getOwnPropertyDescriptor(b.$members,c));if(!r.isAbstract(f)&&h.hasOwnProperty(c)){var a=Object.getOwnPropertyDescriptor(h,c);if("value"in f&&!r.isAbstract(h[c])&&h[c]!==f.value){if("value"in a)h[c]=r();else throw Error("Item "+c+" is already declared as a property and cannot be redefined as a method from "+
b);return}if(("get"in f||"set"in f)&&(a.get!==f.get||a.set!==f.set)){if("value"in f)throw Error("Item "+c+" is already declared as a method and cannot be redefined as a property from "+b);Object.defineProperty(h,c,{get:f.get!==a.get?r:f.get||a.get,set:f.set!==a.set?r:f.set||a.set,configurable:f.configurable});return}}c in h||Object.defineProperty(h,c,f)});Object.getOwnPropertyNames(h).forEach(function(d){var f=Object.getOwnPropertyDescriptor(h,d);(!c.hasOwnProperty(d)||r.isAbstract(Object.getOwnPropertyDescriptor(c,
d)))&&Object.defineProperty(c,d,f)});return c}function p(c,d,f,a,$super){a=void 0===a?!1:a;Object.getOwnPropertyNames(f.$members).forEach(function(b){var j=C({})(Object.getOwnPropertyDescriptor(f.$members,b));if(r.isAbstract(j))if(j.value&&!a&&!(b in d)&&!(b in $super)){if(!l(b,j.value,d,$super))throw Error("Class "+c+" does not implement abstract property/method "+(j.value.$altNames&&j.value.$altNames[0]||b));}else{if(j.get||j.set){if(!a&&!(b in d)&&!(b in $super)&&!l(b,j.get?j.get:j.set,d,$super))throw Error("Class "+
c+" does not implement abstract property "+(j.get.$altNames&&j.get.$altNames[0]||j.set.$altNames&&j.set.$altNames[0]||b));var h=Object.getOwnPropertyDescriptor(d,b)||yfiles.lang.Object.getPropertyDescriptor($super,b),h=h.value?h.value:h;if(j.get&&!h.get)throw Error("Class "+c+" does not implement accessor for property "+b);if(j.set&&!h.set)throw Error("Class "+c+" does not implement mutator for property "+b);}}else!(b in d)&&!(b in $super)&&Object.defineProperty(d,b,j)})}function l(c,d,f,$super){if(d.$altNames){var d=
d.$altNames,a=d[0]==c?d[1]:d[0];if(a in f)return a=Object.getOwnPropertyDescriptor(f,a),1<d.length&&M(a,d,"$altNames"),Object.defineProperty(f,c,a),!0;if(a in $super)return a=Object.getOwnPropertyDescriptor($super,a),1<d.length&&M(a,d,"$altNames"),Object.defineProperty($super,c,a),!0}return!1}function T(c,d,f){s=!0;f.name=c;f.types=d;f.type=A.TRAIT;f.isAbstract=!0;c=new q(f);s=!1;return c}function B(c){if(void 0===q)return S;s=!0;c=new q(c);s=!1;return c}function v(c,d,$super,a,b){d.getClass||Object.defineProperty(d.prototype,
"getClass",{value:function(){return d.$class}});d.isInstance=function(c){return d.$class.isInstance(c)};d.$super=$super.prototype;var H={};H[c]=!0;null!==a&&G(a.$class.types,H);$super.$class&&$super.$class.types&&G($super.$class.types,H);b.name=c;b.constructor=d;b.$extends=$super;b.types=H;b.hasOwnProperty("type")||(b.type=A.CLASS);b.hasOwnProperty("isAbstract")||(b.isAbstract=!0);"yfiles.lang.Class"===c?N[c]=d.$class=B(b):d.$class=Object.freeze(B(b))}function z(c,d){if(y(c.value))c.enumerable=!1,
c.configurable="$clinit"===d;return!1}function V($super){var d=yfiles&&yfiles.lang&&yfiles.lang.Object&&yfiles.lang.Object.getPropertyDescriptor||Object.getOwnPropertyDescriptor;return function(f,a){var b=d($super,a);if(b&&(y(f.get)||y(f.set))){if(!y(f.set)&&y(b.set))f.set=function(d){b.set.call(this,d)};if(!y(f.get)&&y(b.get))f.get=function(){return b.get.call(this)}}}}function E(){return function(c,d){if(y(c.value))try{c.value.displayName=d}catch(f){}return c}}function C(c){return function(d,f){if(d.value&&
"[object Object]"===Object.prototype.toString.call(d.value)){if(d.value.hasOwnProperty("$meta")){var d=d.value,a=d.$meta;if(!c.hasOwnProperty("$meta"))c.$meta={};c.$meta[f]=a;if("undefined"!==typeof d.value)void 0===d.writable&&(d.writable=!0);void 0===d.configurable&&(d.configurable=!0);void 0===d.enumerable&&(d.enumerable=!0);return d}if(d.value.hasOwnProperty("get")||d.value.hasOwnProperty("set"))return void 0===d.value.configurable&&(d.value.configurable=!0),void 0===d.value.enumerable&&(d.value.enumerable=
!0),d.value}return d}}function L(c,$super,f){var a={};Object.getOwnPropertyNames(c).forEach(function(b){var e=$super,j=Object.getOwnPropertyDescriptor(c,b),h=yfiles.mappings.hasOwnProperty(b)&&yfiles.mappings[b];if(h&&!Array.isArray(h))Object.defineProperty(a,h,j);else{if(Array.isArray(h))1<h.length&&M(j,h,"$altNames");else if((e||f)&&yfiles.lang&&yfiles.lang.Object)e=e&&yfiles.lang.Object.getPropertyDescriptor(e.prototype,b)||f&&yfiles.lang.Object.getPropertyDescriptor(f.$members,b),null!==e&&(h=
e.value&&e.value.$altNames||e.get&&e.get.$altNames||e.set&&e.set.$altNames||void 0),"undefined"!==typeof h&&1<h.length&&M(j,h,"$altNames");if(Array.isArray(h))for(b=h.length-1;0<=b;b--)(0==b||1==yfiles.debuglevel)&&D(j),Object.defineProperty(a,h[b],j);else Object.defineProperty(a,b,j)}});if(c.constructor&&"[object Object]"===Object.prototype.toString.call(c.constructor)&&"undefined"===typeof c.constructor.$meta)a.constructor=L(c.constructor);if(c.$static)a.$static=L(c.$static);return a}function M(c,
d,f){if("undefined"!==typeof c.value)if("[object Object]"===Object.prototype.toString.call(c.value))if(c.value.hasOwnProperty("get")){if(c.value.get==r)c.value.get=function(){},c.value.get.abstract=yfiles.lang.AbstractProperty;c.value.get[f]=d}else if(c.value.hasOwnProperty("set")){if(c.value.set==r)c.value.set=function(){},c.value.set.abstract=yfiles.lang.AbstractProperty;c.value.set[f]=d}else if(c.value.hasOwnProperty("$meta")){if(c.value.value==r)c.value.value=c.value.value();c.value.value[f]=
d}else{if(c.value==r)c.value=c.value();c.value[f]=d}else{if(c.value==r)c.value=c.value();c.value[f]=d}else"undefined"!==typeof c.get?c.get[f]=d:"undefined"!==typeof c.set&&(c.set[f]=d)}function K(c,d,f,a,b,e,j){Object.getOwnPropertyNames(c).forEach(function(h){a:{var g=d,u=Object.getOwnPropertyDescriptor(c,h),i=u;if(u.value&&u.value.hasOwnProperty("$meta"))u=u.value;if(u.value instanceof window.yfiles.TypeDefinition)u.value.$$indexName$=f?f+h:h,Object.defineProperty(c,h,i);else{var k=f?f+(b?"_":"")+
h:h;if("constructor"==h)if("[object Function]"==Object.prototype.toString.call(u.value))k=f,g=!0;else break a;else g&&"default"==h&&(k=f);var u=yfiles.mappings&&yfiles.mappings[f]&&yfiles.mappings[f][0],m,k=yfiles.typeinfo.hasOwnProperty(k)&&yfiles.typeinfo[k];if(!k&&(e||j)&&"constructor"!=h){var l=e&&yfiles.lang.Object.getPropertyDescriptor(e.prototype,h)||j&&yfiles.lang.Object.getPropertyDescriptor(j.$members,h);l&&(k=l.value&&l.value.$typeInfo&&l.value.$typeInfo.typeInfo||l.set&&l.set.$typeInfo&&
l.set.$typeInfo.typeInfo||l.get&&l.get.$typeInfo&&l.get.$typeInfo.typeInfo||void 0,m=l.value&&l.value.$altNames&&l.value.$altNames[0]||l.set&&l.set.$altNames&&l.set.$altNames[0]||l.get&&l.get.$altNames&&l.get.$altNames[0]||void 0)}k&&(m=(a?a+".":"")+(m||yfiles.mappings&&yfiles.mappings[h]&&yfiles.mappings[h][0]||h),M(i,{typeInfo:k,clearName:m,classShortName:u,isConstructor:g},"$typeInfo"),g&&("constructor"==h||"default"==h)&&D(i),Object.defineProperty(c,h,i))}}});c.constructor&&"[object Object]"===
Object.prototype.toString.call(c.constructor)&&"undefined"===typeof c.constructor.$meta&&K(c.constructor,!0,f,a);c.$static&&K(c.$static,!1,f,a,!0)}function D(c){if(-1!=yfiles.debuglevel){var d=!1,f,a,b;if(c.value)if(f=c.value.$typeInfo)b=c,a=c.value;else if(f=c.value.value&&c.value.value.$typeInfo)b={},Object.getOwnPropertyNames(c.value).forEach(function(d){b[d]=c.value[d]}),c.value=b,a=b.value;else if(f=c.value.get&&c.value.get.$typeInfo||c.value.set&&c.value.set.$typeInfo)d=!0,b={},Object.getOwnPropertyNames(c.value).forEach(function(d){b[d]=
c.value[d]}),c.value=b,a=c.value.set;if(a&&f){var e=f.clearName,j=f.typeInfo,h=f.classShortName;if(!r.isAbstract(a)){var g=a;a=function(){var c;if(f.isConstructor){if((c=this.$class||this[h]&&this[h].$class)&&!c.isSubclassOf(yfiles.lang.Attribute.$class))throw Error("Illegal operation: constuctor "+e+" is used without new keyword.");}else if(this&&!this.$class&&!this.getClass)throw Error("Illegal operation: method "+e+" is used with new keyword.");var d=j.length/2;if(d!=arguments.length)if(d>arguments.length)for(c=
arguments.length;c<d;c++){if(0===(j[2*c]&4))throw Error("Argument error in "+e+": wrong number of arguments. Expected "+d+", got "+arguments.length);}else throw Error("Argument error in "+e+": wrong number of arguments. Expected "+d+", got "+arguments.length);d=0;if(!f.cache){f.cache=Array(j.length);for(c=0;c<arguments.length;c++,d+=2){var a=j[d],b=j[d+1];if("Object"==b)f.cache[d+1]=Object,f.cache[d]=0|a&16;else switch(a&3){case 0:for(var x=b.split("."),b=window,n=0,i=x.length;n<i&&!(b=b[x[n]],!b);n++);
b?b.$class&&"Enum"==b.$class.type?(f.cache[d+1]=b,f.cache[d]=1):b.$class&&"Trait"==b.$class.type?(f.cache[d+1]=b,f.cache[d]=2):(f.cache[d+1]=b,f.cache[d]=3):(f.cache[d+1]=Object,f.cache[d]=0);break;case 1:throw new Exception;case 2:f.cache[d+1]=b,f.cache[d]=4}4==(a&4)&&(f.cache[d]|=16)}d=0}for(c=0;c<arguments.length;c++,d+=2)if(x=arguments[c],a=f.cache[d],b=f.cache[d+1],"undefined"==typeof x){if(16!==(a&16))throw Error("Argument error in "+e+": parameter "+c+" is undefined.");}else{n=!1;switch(a&
15){case 1:n=!b.$class.isInstance(x);break;case 2:n=null!==x&&!b.$class.isInstance(x);break;case 3:n=null!==x&&!(x instanceof b);break;case 4:n=null!==x&&typeof x!=b}if(n)throw a=x&&x.getClass?x.getClass().fullName:null!=x?typeof x:"null",Error("Argument error in "+e+": incorrect type for parameter "+c+". Expected "+(b.$class&&b.$class.fullName||j[d+1])+" got "+a+".");}return g.apply(this,arguments)};if(g.$typeInfo)a.$typeInfo=g.$typeInfo;if(g.$altNames)a.$altNames=g.$altNames;d?b.set=a:(a.toString=
function(){for(var c="function "+e+"(",d=0;d<j.length;d+=2){0<d&&(c+=", ");var a=j[d+1];if(2>(j[d]&3)){var f=yfiles.lang.Class.forName(a);if(f&&f.fullName)a=f.fullName}c+=a}return c+")"},b.value=a)}}}}var y=yfiles.lang.isFunction,G=yfiles.lang.copyOwnTo,Q=yfiles.lang.defineInvisibleProperty,N={},U=1,W=1,s=!1,R,A=Object.freeze({TRAIT:"Trait",CLASS:"Class",ENUM:"Enum",STRUCT:"Struct",ATTRIBUTE:"Attribute"}),S={name:"yfiles.lang.Class",fullName:"yfiles.lang.Class",types:{"yfiles.lang.Class":!0}},k,I=
{},q=b.Class=a("Class",{$extends:S,constructor:function(c,d){var h;if(!(this instanceof q))return a(c,d,null);if(!s)throw Error("Cannot create a new instance of yfiles.lang.Class");var f=c.name;this.fullName=f;var b=f.lastIndexOf(".");this.namespace=0<b?f.substr(0,b):"";this.name=f.substr(b+1);h=this.$$assemblyName$0=f.split(".")[0],f=h;I.hasOwnProperty(f)||(I[f]=null);this.types=c.types;this.isAnonymous=c.isAnonymous;this.isAbstract=c.isAbstract;this.isFlagsEnum=c.isFlagsEnum;this.isArray=!1;this._fields=
[];this._valueTypeFields=[];this._membersCache={bindings:0,members:null};this._propertyCache={};this.type=c.type;Q(this,"$yfiles___hashcode",yfiles.lang.HashCode.newHashCode());this.$meta=c.$meta||{};if(this.isClass||this.isEnum)this.$extends=c.$extends,this.$$constructor$0=c.constructor},makeArrayType:function(c){"undefined"===typeof c&&(c=1);s=!0;var d=this.hashCode()*(31^c.hashCode()),c=Object.create(this,{isArray:{value:!0,writable:!0,configurable:!0},rank:{value:c,writable:!0,configurable:!0},
$yfiles___hashcode:{value:d,writable:!0,configurable:!0}});s=!1;return c},getArrayRank:function(){return this.isArray&&this.rank||0},getElementType:function(){return this.isArray&&Object.getPrototypeOf(this)||this},toString:function(){return"[object yfiles.lang.Class<"+this.fullName+">]"},hashCode:function(){return this.$yfiles___hashcode},clone:function(){return this},equals:function(c){return c===this},isInstance:function(c){if("Enum"===this.type){e();for(var d=this.getFields(k.BindingFlags.PUBLIC|
k.BindingFlags.STATIC),a=this.isFlagsEnum,b=0,n=0;n<d.length;n++){var g=d[n].getValue(null);if(a)b|=g;else if(g===c)return!0}return a?(b&c)===c:!1}return c&&c.getClass&&!!c.getClass().types[this.fullName]},isSubclassOf:function(c){return c&&c!==this&&(!0===this.types[c.fullName]||c===yfiles.lang.Object.$class)},isAssignableFrom:function(c){return c&&(c.fullName==this.fullName||c.isSubclassOf(this))},get baseType(){return this.$extends&&this.$extends.$class||null},get assembly(){var c=this.$$assemblyName$0,
d=I[c];d||(I[c]=d=new yfiles.lang.Assembly(c));return d},get isClass(){return this.type===A.CLASS},get isEnum(){return this.type===A.ENUM},get isInterface(){return this.type===A.TRAIT},get isPrimitive(){return"yfiles.lang.Number"===this.fullName||"yfiles.lang.String"===this.fullName||"yfiles.lang.Boolean"===this.fullName},get isPublic(){return!0},get isValueType(){return this.isPrimitive||this.isSubclassOf(yfiles.lang.Struct.$class)},get reflectedType(){return this},get memberType(){e();return k&&
k.MemberTypes.TypeInfo||32},newInstance:function(){if(0===arguments.length&&this.baseType==yfiles.lang.Struct.$class){var c=this.getMethod("createDefault");if(null!=c)return c.invoke(this,[])}c=this.$$constructor$0;if(null===c)throw Error("Cannot instantiate a new object of type "+this.fullName+" using reflection.");var d=Object.create(c.prototype);c.apply(d,arguments);return d},findInterfaces:function(c,d){var a=[];Object.getOwnPropertyNames(this.types).forEach(function(b){b=q.forName(b);b.isInterface&&
c(b,d)&&a.push(b)},this);return a},getInterfaces:function(){return this.findInterfaces(function(c){return!c.isAnonymous},null)},$$isValidName$0:function(c,d){if("$class"===c||"$super"===c)return!1;var a=Object.getOwnPropertyDescriptor(d,c);if(!a)return!1;a=a.value&&a.value.$altNames||a.get&&a.get.$altNames||a.set&&a.set.$altNames||void 0;return!("undefined"!==typeof a&&a[0]!==c)},findMembers:function(c,d,a,b,n){var i=this._membersCache;if(i.members&&i.reflectedType==c&&i.bindingAttr==a&&i.memberType==
d){if(!l)return i.members;for(var j=0;j<i.members.length;j++)l.push(i.members[j]);return l}e();b||(b=function(){return!0});var h=this.Object.prototype,l=[];(a&k.BindingFlags.INSTANCE)===k.BindingFlags.INSTANCE&&Object.getOwnPropertyNames(h).forEach(function(e){if(this.$$isValidName$0(e,h)){var j=m(e,h,this);(d&j)===j&&(e=g(h,e,j,c,this,!1))&&((a&k.BindingFlags.PUBLIC)===k.BindingFlags.PUBLIC&&e.isPublic||(a&k.BindingFlags.NON_PUBLIC)===k.BindingFlags.NON_PUBLIC&&!e.isPublic)&&b(e,n)&&l.push(e)}},
this);if((a&k.BindingFlags.STATIC)===k.BindingFlags.STATIC)h=this.Object,Object.getOwnPropertyNames(h).forEach(function(e){if(this.$$isValidName$0(e,h)){var j=m(e,h,this);(d&j)===j&&"arguments"!==e&&"length"!==e&&"name"!==e&&"caller"!==e&&"displayName"!==e&&"prototype"!==e&&(e=g(h,e,j,c,this,!0))&&((a&k.BindingFlags.PUBLIC)===k.BindingFlags.PUBLIC&&e.isPublic||(a&k.BindingFlags.NON_PUBLIC)===k.BindingFlags.NON_PUBLIC&&!e.isPublic)&&b(e,n)&&l.push(e)}},this);if(0===(a&k.BindingFlags.DECLARED_ONLY))(h=
this.baseType)&&(l=l.concat(h.findMembers(c,d,a,b,n)));this._membersCache.bindingAttr=a;this._membersCache.reflectedType=c;this._membersCache.memberType=d;return this._membersCache.members=l},getMembers:function(c){e();return this.findMembers(this,k.MemberTypes.ALL,c||k.BindingFlags.INSTANCE|k.BindingFlags.PUBLIC|k.BindingFlags.STATIC|k.BindingFlags.DECLARED_ONLY,function(c){return c.isPublic})},getMember:function(c,d){e();return this.findMembers(this,k.MemberTypes.ALL,d||k.BindingFlags.INSTANCE|
k.BindingFlags.PUBLIC|k.BindingFlags.STATIC|k.BindingFlags.DECLARED_ONLY,function(d){return d.name===c&&d.isPublic})},getConstructors:function(c){e();return this.findMembers(this,k.MemberTypes.CONSTRUCTOR,c||k.BindingFlags.INSTANCE|k.BindingFlags.PUBLIC|k.BindingFlags.STATIC|k.BindingFlags.DECLARED_ONLY)},getFields:function(c){e();return this.findMembers(this,k.MemberTypes.FIELD,c||k.BindingFlags.INSTANCE|k.BindingFlags.PUBLIC|k.BindingFlags.STATIC)},getField:function(c,d){for(var a=this.getFields(d),
b=0,e=a.length;b<e;b++)if(a[b].name===c)return a[b];return null},getMethods:function(c){e();return this.findMembers(this,k.MemberTypes.METHOD,c||k.BindingFlags.INSTANCE|k.BindingFlags.PUBLIC|k.BindingFlags.STATIC)},getMethod:function(c,d,a){for(var d=this.getMethods(a),a=0,b=d.length;a<b;a++)if(d[a].name===c)return d[a];return null},getNestedTypes:function(c){e();return this.findMembers(this,k.MemberTypes.NESTED_TYPE,c||k.BindingFlags.INSTANCE|k.BindingFlags.PUBLIC|k.BindingFlags.STATIC|k.BindingFlags.DECLARED_ONLY)},
getNestedType:function(c,d){for(var a=this.getNestedTypes(d),b=0,e=a.length;b<e;b++)if(a[b].name===c)return a[b];return null},getProperties:function(c){e();if(this._propertyCache[c])return this._propertyCache[c];var d=this.findMembers(this,k.MemberTypes.PROPERTY,c||k.BindingFlags.INSTANCE|k.BindingFlags.PUBLIC|k.BindingFlags.STATIC);return this._propertyCache[c]=d},getProperty:function(c,d,a,b){d=this.getProperties(b);a=0;for(b=d.length;a<b;a++)if(d[a].name===c)return d[a];return null},getGenericArguments:function(){return[]},
getAttributesFor:function(c){try{if(this.$meta.hasOwnProperty(c)){var d=this.$meta[c];y(d)&&(d=d(),this.$meta[c]=d);if(d&&0<d.length)return y(d[0])&&(d=d.map(function(c){return c()}),this.$meta[c]=d),d}return[]}catch(a){throw console.log(a),Error("Could not get meta attributes for "+this.name+"."+c);}},getCustomAttributes:function(c){var d=this.getAttributesFor(this.fullName);if(c)(c=this.baseType)&&c instanceof q&&(d=d.concat(c.getCustomAttributes(!0)));return d},getCustomAttributesOfType:function(c,
d){for(var a=this.getCustomAttributes(d),b=[],e=0,g=0;g<a.length;g++){var j=a[g];c.isInstance(j)&&(b[e++]=j)}return b},isDefined:function(c,d){for(var a=this.getCustomAttributes(d),b=0,e=a.length;b<e;b++)if(c.isInstance(a[b]))return!0;return!1},get Object(){return this.$$constructor$0},$static:{forName:function(c){var d=N[c];if(void 0===d){for(var c=c.split("."),d=window,a=0,b=c.length;a<b;a++){if("undefined"===typeof d[c[a]])return null;d=d[c[a]]}return null!=d?d.$class:null}return d},getAssemblies:function(){var c=
[];Object.getOwnPropertyNames(I).forEach(function(d){var a=I[d];a||(I[d]=a=new yfiles.lang.Assembly(d));c.push(a)});return c}}}),s=!0;q.$class=new q({name:"yfiles.lang.Class",types:{"yfiles.lang.Class":!0},type:A.CLASS,isAnonymous:!1,isAbstract:!0,constructor:null,$private:{},$extends:Object});s=!1;b.Assembly=q("Assembly",{constructor:function(c){this.$$name$0=c},get fullName(){return this.$$name$0},isDefined:function(c){return 0<this.getCustomAttributesOfType(c).length},getCustomAttributes:function(){var c=
this.$$name$0,d=J[c];if(!d)return[];if(d&&0<d.length){if(y(d[0])){for(var a=[],b=0;b<d.length;b++)for(var e=(0,d[b])(),g=0;g<e.length;g++)a.push(e[g]());return J[c]=a}return d}return[]},getCustomAttributesOfType:function(c){for(var d=this.getCustomAttributes(),a=[],b=0,e=0,g=d.length;e<g;e++){var j=d[e];c.isInstance(j)&&(a[b++]=j)}return a},getType:function(c){return yfiles.lang.Class.forName(c)},$static:{getExecutingAssembly:function(){return new yfiles.lang.Assembly("yworks")}}});var F={constructor:function(){},
toString:function(){return"[object "+this.getClass().name+"#"+this.hashCode().toString(16)+"]"},equals:function(c){return this===c},getClass:function(){return Object.getPrototypeOf(this).constructor.$class},hashCode:function(){var c=this.$$hashCode$0;void 0===c&&(c=yfiles.lang.HashCode.newHashCode(),Q(this,"$$hashCode$0",c));return c},memberwiseClone:function(){var c=this.getClass(),d=Object.create(c.Object.prototype);c.isValueType||Q(d,"$$hashCode$0",yfiles.lang.HashCode.newHashCode());if(0===c._fields.length&&
0===c._valueTypeFields.length){for(var a=Object.getOwnPropertyNames(this),b=0,e=a.length;b<e;b++){var g=a[b],j=this[g];j instanceof yfiles.lang.Struct?(c._valueTypeFields.push(g),d[g]=j.clone()):(c._fields.push(g),d[g]=j)}return d}a=c._fields;b=0;for(e=a.length;b<e;b++)g=a[b],d[g]=this[g];c=c._valueTypeFields;b=0;for(e=c.length;b<e;b++)g=c[b],d[g]=this[g].clone();return d},getOwnProperty:function(c,a){var a=a||this,b=yfiles.lang.Object.getPropertyDescriptor(this,c);return null===b?null:{get:b.get?
b.get.bind(a):void 0,set:b.set?b.set.bind(a):void 0}},$static:{equals:function(c,a){return c===a||c&&a&&c.equals&&c.equals(a)},referenceEquals:function(c,a){return c===a},getPropertyDescriptor:function(c,a){var b=Object.getOwnPropertyDescriptor(c,a);return!b&&c.getClass&&c.getClass()!==yfiles.lang.Object?yfiles.lang.Object.getPropertyDescriptor(Object.getPrototypeOf(c),a):b||null}}};b.Object=q("Object",F);s=!0;F.name="yfiles.lang.Object";F.type=A.CLASS;F.types={};F.isAbstract=!1;F.isAnonymous=!1;
F=new q(F);F.isInstance=function(c){return null!==c&&"undefined"!==typeof c};b.Object.$class=Object.freeze(F);var s=!1,r=b.Abstract=q("Abstract",{constructor:function(){if(!(this instanceof r))return new r},$static:{isAbstract:function(c){return c instanceof r||c===r||c===X||c===Y?!0:c&&c.value?r.isAbstract(c.value):c&&(c.get||c.set)?c.get&&r.isAbstract(c.get)||c.set&&r.isAbstract(c.set):"function"==typeof c&&r.isAbstract(c["abstract"])?!0:!1}}}),X=b.AbstractMethod=q("AbstractMethod",{$extends:yfiles.lang.Abstract,
constructor:function(){return r()}}),Y=b.AbstractProperty=q("AbstractProperty",{$extends:yfiles.lang.Abstract,constructor:function(){return r()}}),Z=0,P=b.Attribute=q("Attribute",{$extends:yfiles.lang.Object,constructor:function(c,d){if(!(this instanceof P)){var b=!1;"[object String]"!==Object.prototype.toString.call(c)&&(d=c,c="AnonymousAttribute$"+Z++,b=!0);d.$extends||(d.$extends=P);var e,g=function(){return Object.create(e.prototype)};if(d.hasOwnProperty("constructor"))if(y(d.constructor))d.constructor=
t(d.constructor,g);else{d.constructor["default"]||(d.constructor["default"]=function(){});for(var i=Object.getOwnPropertyNames(d.constructor),j=0,h=i.length;j<h;j++){var k=i[j];d.constructor[k]=t(d.constructor[k],g)}}else d.constructor=t(function(){},g);return e=a(c,d,{isAnonymous:b,type:A.ATTRIBUTE})}},$static:{getCustomAttribute:function(c,a){var b=c.getCustomAttributesOfType(a,!1);return 0<b.length?b[0]:null}}}),O=b.Trait=function(c,a){var b=s,e={isAnonymous:!1};if("string"!==typeof c&&!a)a=c,
c="AnonymousTrait$"+W++,e.isAnonymous=!0;var g=0<w.length?w+"."+c:c,i=function(){throw Error("Cannot instantiate trait "+g);};i.$name=g;i.toString=function(){return g};yfiles.typeinfo&&-1!=yfiles.debuglevel&&(K(a,!1,a.$$indexName$,c),delete a.$$indexName$);yfiles.mappings&&(a=L(a));var j=a.hasOwnProperty("$static")?a.$static:{};delete a.$static;e.$meta||(e.$meta={});if(a.$meta)e.$meta[g]=a.$meta,delete a.$meta;G(j,i);i.$members={};G(a,i.$members,C(e));j={};j[g]=!0;if(a.hasOwnProperty("$with")){var h=
a.$with;delete a.$with;delete i.$members.$with;if(h.hasOwnProperty("$members"))G(h.$class.types,j),h=[i.$members,e,h];else{for(var k=0,l=h.length;k<l;k++){if(void 0==h[k])throw Error("Trying to implement undefined trait in "+(R||g)+" at index "+k);G(h[k].$class.types,j)}h.unshift(i.$members,e)}o.apply(null,h)}i.$class=Object.freeze(T(g,j,e));i.isInstance=function(a){return i.$class.isInstance(a)};if(!b)i=Object.freeze(i),N[g]=i.$class;return i};b.Trait.isTrait=function(a){return a.$class&&a.$class.isTrait};
(function(){var c=1,d=b.Enum=q("Enum",{constructor:function(b,e){if(this instanceof d)return this;var g=!1;"string"!==typeof b&&!e&&(e=b,b="AnonymousEnum$"+c++,g=!0);if("undefined"===typeof e.$static)e.$static={};e.$extends=yfiles.lang.Enum;var i=e.$Flags||!1,j=0;Object.getOwnPropertyNames(e).forEach(function(a){var c=e[a];"$static"!==a&&"$extends"!==a&&"$Flags"!==a&&("undefined"===typeof c?c=j:j=c,e.$static[a]=c,delete e[a],j++)});var h=a(b,e,{isAnonymous:g,type:A.ENUM,isFlagsEnum:i});h.toString=
function(){return"[object "+h.$class.name+"]"};h.contains=function(a,c){return(c&a)===c};return h},$static:{parse:function(a,c,b){var d=a.Object;if(void 0===b||!b||d[c])return d[c];var e;for(e=0,b=yfiles.lang.Enum.getFilteredOwnPropertyNames(d);e<b.length;e++){var g=b[e];if(g.toLowerCase()===c.toLowerCase())return d[g]}throw new yfiles.system.ArgumentException.FromMessage("Enum token "+c+" undefined in "+a);},getName:function(a,c){if(a.isEnum){for(var b=a.Object,d=yfiles.lang.Enum.getFilteredOwnPropertyNames(b),
e=0,g=d.length;e<g;e++){var i=d[e];if(b[i]===c)return i}throw Error("Unknown value "+c+" for Enum "+a.fullName);}throw Error("Not an enum: "+a.fullName);},getFilteredOwnPropertyNames:function(a){var c=Object.getOwnPropertyNames(a);return c=c.filter(function(c){return a.propertyIsEnumerable(c)&&"function"!==typeof a[c]&&"$class"!==c&&"displayName"!==c&&"$super"!=c})}}})})();(function(){var a=0,d=b.Struct=q("Struct",{$extends:b.Object,constructor:function(b,e){if(this instanceof d)return this;"string"!==
typeof b&&!e&&(e=b,b="AnonymousStruct$"+a++);var g=function(){};e.$extends=yfiles.lang.Struct;e.clone=e.clone||function(){var a=this.getClass(),c=new g;if(0===a._fields.length&&0===a._valueTypeFields.length){for(var b=Object.getOwnPropertyNames(this),d=0,e=b.length;d<e;d++){var f=b[d],i=this[f];i instanceof yfiles.lang.Struct?(a._valueTypeFields.push(f),c[f]=i.clone()):(a._fields.push(f),c[f]=i)}return c}b=a._fields;d=0;for(e=b.length;d<e;d++)f=b[d],c[f]=this[f];a=a._valueTypeFields;d=0;for(e=a.length;d<
e;d++)f=a[d],c[f]=this[f].clone();return c};var i;i=q(b,e);g.prototype=i.prototype;if(!i.createDefault)i.createDefault=function(){var a=new g;a.$$init$0&&a.$$init$0();return a};return i},hashCode:function(){var a=this.getClass();if(0===a._fields.length&&0===a._valueTypeFields.length)for(var c=Object.getOwnPropertyNames(this),b=0,d=c.length;b<d;b++){var e=c[b];this[e]instanceof yfiles.lang.Struct?a._valueTypeFields.push(e):a._fields.push(e)}e=1;c=a._fields;b=0;for(d=c.length;b<d;b++){var g=this[c[b]];
g&&!(g instanceof yfiles.lang.Object)&&g.hashCode&&(e=(e<<5)-e+g.hashCode())}c=a._valueTypeFields;b=0;for(d=c.length;b<d;b++)(g=this[c[b]])&&g.hashCode&&(e=(e<<5)-e+g.hashCode());return e},equals:function(a){if(null==a||!this.getClass().isInstance(a))return!1;for(var c=Object.getOwnPropertyNames(this),b=0,d=c.length;b<d;b++){var e=c[b];if(this.propertyIsEnumerable(e)){if(!a.hasOwnProperty(e))return!1;var g=this[e],e=a[e];if(g!==e){if(null==g||null==e)return!1;if(g instanceof yfiles.lang.Struct)if(g.equals(e))continue;
else return!1;if(!yfiles.lang.isFunction(g)||!g.equals||!g.equals(e))return!1}}}return!0}})})();s=!0;b.IComparable=O("IComparable",{compareTo:yfiles.lang.AbstractMethod});s=!0;b.IComparable.$class=new q({name:"yfiles.lang.IComparable",types:{"yfiles.lang.IComparable":!0},type:A.TRAIT,isAnonymous:!1,isAbstract:!0,constructor:b.IComparable});b.IComparable=Object.freeze(b.IComparable);N[b.IComparable.$class.fullName]=b.IComparable.$class;b.IComparable.$class.isInstance=function(a){var b=typeof a;return"number"===
b||"string"===b||"boolean"===b?!0:q.prototype.isInstance.apply(this,[a])};s=!1;s=!0;b.IObjectComparable=O("IObjectComparable ",{compareToObject:yfiles.lang.AbstractMethod});s=!0;b.IObjectComparable.$class=new q({name:"yfiles.lang.IObjectComparable",types:{"yfiles.lang.IObjectComparable":!0},type:A.TRAIT,isAnonymous:!1,isAbstract:!0,constructor:b.IObjectComparable});b.IObjectComparable=Object.freeze(b.IObjectComparable);N[b.IObjectComparable.$class.fullName]=b.IObjectComparable.$class;b.IObjectComparable.$class.isInstance=
function(a){var b=typeof a;return"number"===b||"string"===b||"boolean"===b?!0:q.prototype.isInstance.apply(this,[a])};s=!1;b.Number=q("Number",{});s=!0;b.Number.$class=new q({name:"yfiles.lang.Number",types:{"yfiles.lang.IComparable":!0,"yfiles.lang.IObjectComparable":!0},type:A.CLASS,isAnonymous:!1,isAbstract:!1,constructor:Number,$extends:Object});b.Number.$class.isInstance=function(a){return"[object Number]"===Object.prototype.toString.call(a)};s=!1;b.String=q("String",{});s=!0;b.String.$class=
new q({name:"yfiles.lang.String",types:{"yfiles.lang.IComparable":!0,"yfiles.lang.IObjectComparable":!0},type:A.CLASS,isAnonymous:!1,isAbstract:!1,constructor:String,$extends:Object});b.String.$class.isInstance=function(a){return"[object String]"===Object.prototype.toString.call(a)};s=!1;b.Boolean=q("Boolean",{});s=!0;b.Boolean.$class=new q({name:"yfiles.lang.Boolean",types:{"yfiles.lang.IComparable":!0,"yfiles.lang.IObjectComparable":!0},type:A.CLASS,isAnonymous:!1,isAbstract:!1,constructor:Boolean,
$extends:Object});b.Boolean.$class.isInstance=function(a){return"[object Boolean]"===Object.prototype.toString.call(a)};s=!1});yfiles.module("yfiles.lang",function(b){b.Exception=yfiles.lang.Class("Exception",{$extends:Error,constructor:function(a){yfiles.lang.copyOwnTo(Error(a),this);this.message=a;this.name=this.getClass().name}})});yfiles.module("yfiles.crypto",function(b){b.SHA1={hash:function(a){for(var b=Array(a.length),e=0;e<a.length;e++)b[e]=a.charCodeAt(e);for(var g=8*b.length,a=[],m=e=0;e<
b.length;e++,m+=8)a[m>>>5]|=(b[e]&255)<<24-m%32;var b=1732584193,e=4023233417,m=2562383102,t=271733878,o=3285377520;a[g>>>5]|=128<<24-g%32;a[(g+64>>>9<<4)+15]=g;for(g=0;g<a.length;g+=16){for(var p=[],l=0;79>=l;l++)p[l]=16>l?a[g+l]:(p[l-3]^p[l-8]^p[l-14]^p[l-16])<<1|(p[l-3]^p[l-8]^p[l-14]^p[l-16])>>>31;for(var w=b,B=e,v=m,z=t,D=o,l=0;79>=l;l++){var E=0,C=0;0<=l&&19>=l?(E=B&v|~B&z,C=1518500249):20<=l&&39>=l?(E=B^v^z,C=1859775393):40<=l&&59>=l?(E=B&v|B&z|v&z,C=2400959708):60<=l&&79>=l&&(E=B^v^z,C=3395469782);
E=(w<<5|w>>>27)+E+D+C+(p[l]>>>0);D=z;z=v;v=B<<30|B>>>2;B=w;w=E}b+=w;e+=B;m+=v;t+=z;o+=D}b=[b,e,m,t,o];a=[];for(m=e=0;m<32*b.length;m+=8,e++)a[e]=b[m>>>5]>>>24-m%32&255;b="";for(e=0;e<a.length;e++)b+=(a[e]>>4&15).toString(16)+(a[e]&15).toString(16);return b}}});yfiles.module("yfiles.lang",function(b){b=b.delegate=function(a,b){if(!yfiles.lang.isFunction(a))var e=a,a=a[b],b=e;e=function(){return a.apply(b,arguments)};e.fn=a;e.handler=e;e.target=b;e.hashCode=function(){return yfiles.lang.HashCode.of(a.name||
a.displayName||"")^41*(b&&b.hashCode?b.hashCode():13)};e.equals=function(a){return null==a?!1:a===this?!0:a.target!==this.target||this.fn!==a.fn?!1:!0};return e};b.dynamicInvoke=function(a,b){return a.apply(null,b)};b.createDelegate=function(a,b){var e=function(){for(var e=0,m=a.length;e<m;e++)a[e].apply(b,arguments)};e.handler=a;e.target=b;e.hashCode=function(){for(var b=0,e=0,i=a.length;e<i;e++)b+=a[e].hashCode()^41;return b*(this.target&&this.target.hashCode?this.target.hashCode():13)};e.equals=
function(a){if(null==a)return!1;if(a===this)return!0;if(a.target!==this.target||!yfiles.lang.isArray(a.handler)||a.handler.length!=this.handler.length)return!1;for(var b=0;b<this.handler.length;b++)if(!a.handler[b].equals(this.handler[b]))return!1;return!0};return e};b.getInvocationList=function(a){return!a?[]:a.handler?yfiles.lang.isArray(a.handler)?a.handler:[a.handler]:[a]};b.combine=function(a,b){if(2<arguments.length){for(var e=null,g=0,m=arguments.length;g<m;g++)e=yfiles.lang.delegate.combine(e,
arguments[g]);return e}e=yfiles.lang.isArray;if(null==a)return b;if(null==b)return a;g=[];e(a.handler)?Array.prototype.push.apply(g,a.handler):g.push(a);e(b.handler)?Array.prototype.push.apply(g,b.handler):g.push(b);return yfiles.lang.delegate.createDelegate(g)};b.removeAll=function(a,b){var e=yfiles.lang.delegate.remove,g=null;do g=a,a=e(a,b);while(!g.equals(a));return g};b.remove=function(a,b){if(null==a)return null;if(null==b)return a;if(a===b||a.equals(b))return null;var e=yfiles.lang.isArray,
g=a.handler,m,t,o;if(!e(g)||2>g.length)return a;var p=g.length-1;if(!e(b.handler)){for(m=p;0<=m;m--)if(g[m]===b||g[m].equals(b)){if(1===g.length)return null;if(2===g.length)return g[0===m?1:0];e=Array(p);if(0<m)for(o=0;o<m;o++)e[o]=g[o];if(m<p)for(o=m+1;o<g.length;o++)e[o-1]=g[o];return yfiles.lang.delegate.createDelegate(e)}return a}var l=b.handler;if(l.length>g.length)return a;m=p;a:for(;m>=l.length-1;m--){for(t=0;t<l.length;t++)if(!g[m-t].equals(l[l.length-1-t]))continue a;if(l.length==p)return m==
p?g[0]:g[p];e=Array(g.length-l.length);if(m>=l.length)for(o=0;o<=m-l.length;o++)e[o]=g[o];for(o=m+1,t=o-l.length;o<g.length;o++,t++)e[t]=g[o];return yfiles.lang.delegate.createDelegate(e)}return a}})});
